config/routes.rb
Rails.application.routes.draw do
  root "questionnaires#index"

  resources :questionnaires, only: [:create, :new, :show]
  resources :responses, only: [:create, :index]
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionnaire
  has_many :responses

  validates :name, uniqueness: true
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questions
  has_many :responses, through: :questions

  accepts_nested_attributes_for :questions

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  def index
    @questionnaires = Questionnaire.all
  end

  def new
    @questionnaire = Questionnaire.new
    1.times { @questionnaire.questions.build }
  end

  def create
    @questionnaire = Questionnaire.new(allowed_params)
    if @questionnaire.save
      redirect_to root_path, notice: "Questionnaire created successfully!"
    else
      render 'new'
    end
  end

  def show
    @questionnaire = Questionnaire.find(params[:id])
  end

  private

  def allowed_params
    {
      name: params[:questionnaire][:name],
      questions_attributes: params[:questionnaire][:questions_attributes]
    }
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def index
    @questionnaires = Questionnaire.all
  end

  def create
    name = params[:name]
    create_responses(name)
    redirect_to root_path, notice: "Thank you for your response!"
  end

  private

  def create_responses(name)
    params[:responses].each do |question_id, answer|
      Response.create(
        name: name,
        question_id: question_id.to_i,
        answer: answer
      )
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Everplans</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="full-width">

  <% if flash[:notice] %>
    <div class="success">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <p class="cntr-txt nav-bar">
    <%= link_to "Create New Questionnaire", new_questionnaire_path %>
    &nbsp&nbsp&nbsp&nbsp&nbsp
    <%= link_to "View Responses", responses_path %>
    &nbsp&nbsp&nbsp&nbsp&nbsp
    <%= link_to "All Questionnaires", root_path %>
  </p>

  <div id="content">
    <%= yield %>
  </div>

</div>

</body>
</html>

app/views/questionnaires/index.html.erb
<h1 class="cntr-txt">Existing Questionnaires</h1>
<p class="cntr-txt">
  <%= link_to "New Questionnaire", new_questionnaire_path, class: "button-link new-questionnaire" %>
</p>
<div class="questionnaire-container six-wide shift-three">

  <% @questionnaires.each do |questionnaire| %>
    <div class="questionnaire-name">
      <p class="cntr-txt">
        <%= link_to questionnaire.name, questionnaire_path(questionnaire) %>
      </p>
    </div>
  <% end %>

</div>

app/views/questionnaires/new.html.erb
<h1 class="cntr-txt">Create New Questionnaire</h1>

<div class="six-wide shift-three" id="form-container" data-questions="0">
  <% if @questionnaire.errors.any? %>
    <%@questionnaire.errors.full_messages.each do |msg| %>
      <p class="error-msg"><%= msg %></p>
    <% end %>
  <% end %>

  <%= form_for @questionnaire do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <div class="questions">
      <%= f.fields_for :questions do |question_fields| %>
        <%= question_fields.label :name, "Question 1" %>
        <%= question_fields.text_field :name %>
        <%= question_fields.label :label, "Description" %>
        <%= question_fields.text_field :label %>
      <% end %>
    </div>

    <div class="add-question">
      <%= link_to "Add Question"%>
    </div>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/questionnaires/show.html.erb
<h1 class="cntr-txt"><%= @questionnaire.name %></h1>

<div class="eight-wide shift-two">
  <form action="/responses" method="post">
    <%= hidden_field_tag(request_forgery_protection_token.to_s, form_authenticity_token) %>
    <label for="name">Name</label>
    <input type="text" id="name" name="name">
    <% @questionnaire.questions.each do |question| %>
      <label for="question_<%= question.id %>"><%= question.name %></label>
      <p><%= question.label %></p>
      <input type="text" id="question_<%= question.id %>" name="responses[<%= question.id %>]" class="answer-input">
    <% end %>
    <input type="submit" value="Submit Response">
  </form>
</div>

app/views/responses/index.html.erb
<h1 class="cntr-txt">Responses</h1>

<% @questionnaires.each do |questionnaire| %>
  <div class="response-container eight-wide shift-two">
    <div class="questionnaire-name">
      <%= questionnaire.name %>
    </div>
    <% questionnaire.questions.each_with_index do |question, index| %>
      <div class="question-name">
        Q<%= index + 1 %>: <%= question.name %><br>
        Description: '<%= question.label %>'
      </div>
      <div class="response">
        <% question.responses.each do |response| %>
          <div class="response-name">
            <%= response.name %>
            on <%= response.created_at.strftime("%A, %b %d") %>:
          </div>
          <div class="response-answer">
            "<%= response.answer %>"
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>